---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: true
  notify: Restart nginx

- name: Deploy Nginx config
  ansible.builtin.template:
    src: joomla.conf.j2
    dest: "{{ nginx_conf_path }}"
    mode: "0644"
  notify: Reload nginx

- name: Enable site configuration
  ansible.builtin.file:
    src: "{{ nginx_conf_path }}"
    dest: "{{ nginx_symlink_path }}"
    state: link
  notify: Reload nginx

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Validate Nginx configuration
  ansible.builtin.command: nginx -t
  register: nginx_test
  changed_when: false
  notify: Reload Nginx
