---
- name: Deploy LEMP stack with Joomla
  hosts: all
  become: true
  vars_files:
    - group_vars/all/vars.yml
    - group_vars/all/vault.yml

  roles:
    - role: nginx
    - role: php
    - role: mysql
    - role: initapps
    - role: joomla
